What You're Aiming For
In this checkpoint, we aim to explore and preprocess the billing history of the Tunisian electricity and gas company's customers from 2005 to 2019, focusing on understanding the data structure, handling missing values, performing descriptive analysis, and transforming categorical variables into numerical formats.

Instructions
In this checkpoint, we are going to work on the billing history of the Tunisian electricity and gas company and apply what you learned in pre-processing chapter.

Dataset description : 

The provided dataset contains the billing history of the Tunisian electricity and gas company's customers from 2005 to 2019.

➡️ Dataset link

https://i.imgur.com/AaBqRR5.png

Load the dataset, display the ten first lines, store the results in a variable called 'client_0_bills'.
What is the data type of the 'client_0_bills' variable ?
Display the general information of the dataset and try to answer the following questions : 
How many rows and columns do we have in this dataset ?
How many categorical features are present in the dataset ?
How much memory space does the dataset consume ?
Inspect the dataset for potential missing values.
Select your strategy to handle missing values, and tell us why you had made that choice.
Run a descriptive analysis on numeric features (columns).
Select the bills records for the client with an id ='train_Client_0', using 2 methods.
Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
Delete the 'counter_statue' feature from the Dataframe

In [78]:
import pandas as pd
df = pd.read_csv('STEG_BILLING_HISTORY.csv', low_memory=False)
df.head(10)

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             str
 1   invoice_date          str
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_statue        str
 5   counter_code          int64
 6   reading_remarque      float64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          str
dtypes: float64(2), int64(10), str(4)
memory usage: 546.5 MB

Inspect the dataset for potential missing values.

In [80]:
df.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             0
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [81]:
client_0_bills = df.head(10)
client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [82]:
print('the type of the variable client_0_bills is a',type(client_0_bills).__name__)

the type of the variable client_0_bills is a DataFrame

- How many rows and columns do we have in this dataset ?
There are 10 ligns and 16 columns

In [83]:
print("number of ligns nd columns :", client_0_bills.shape)

number of ligns nd columns : (10, 16)

How many categorical features are present in the dataset ?

How much memory space does the dataset consume ?

In [84]:
df.dropna(inplace=True, subset=["counter_number"])
df.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number             0
counter_statue             0
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [85]:
df.drop(columns=['reading_remarque'], inplace = True)
df.isnull().sum()

client_id               0
invoice_date            0
tarif_type              0
counter_number          0
counter_statue          0
counter_code            0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

Select the bills records for the client with an id ='train_Client_0', using 2 methods.

In [86]:
df[df['client_id'] == 'train_Client_0']

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,2008-11-25,11,1335667.0,0,203,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,2012-07-23,11,1335667.0,0,203,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,2012-11-29,11,1335667.0,0,203,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,2013-07-22,11,1335667.0,0,203,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,2014-07-18,11,1335667.0,0,203,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,2014-11-24,11,1335667.0,0,203,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,2015-11-18,11,1335667.0,0,207,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,2012-03-27,11,1335667.0,0,203,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,2011-03-30,11,1335667.0,0,203,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2013-02-12,11,1335667.0,0,203,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,2010-07-22,11,1335667.0,0,203,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,2010-11-24,11,1335667.0,0,203,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,2005-10-17,11,1335667.0,0,203,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2006-02-24,11,1335667.0,0,203,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,2006-06-23,11,1335667.0,0,203,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,2006-10-18,11,1335667.0,0,203,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,2007-06-27,11,1335667.0,0,203,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,2007-10-25,11,1335667.0,0,203,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2007-02-26,11,1335667.0,0,203,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,2008-07-28,11,1335667.0,0,203,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,2009-01-04,11,1335667.0,0,203,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,2009-07-27,11,1335667.0,0,203,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,2009-11-24,11,1335667.0,0,203,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,2010-03-29,11,1335667.0,0,203,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,2008-01-04,11,1335667.0,0,203,1,277,0,0,0,4969,5246,4,ELEC

Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.

In [87]:
mapping = {'ELEC': 1, 'GAZ': 2}
df['counter_type'] = df['counter_type'].map(mapping)
df.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,1,82,0,0,0,14302,14384,4,1
1,train_Client_0,2013-03-29,11,1335667.0,0,203,1,1200,184,0,0,12294,13678,4,1
2,train_Client_0,2015-03-23,11,1335667.0,0,203,1,123,0,0,0,14624,14747,4,1
3,train_Client_0,2015-07-13,11,1335667.0,0,207,1,102,0,0,0,14747,14849,4,1
4,train_Client_0,2016-11-17,11,1335667.0,0,207,1,572,0,0,0,15066,15638,12,1

In [88]:
df.drop(columns=['counter_statue'],inplace= True)
df.head()

,client_id,invoice_date,tarif_type,counter_number,counter_code,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,203,1,82,0,0,0,14302,14384,4,1
1,train_Client_0,2013-03-29,11,1335667.0,203,1,1200,184,0,0,12294,13678,4,1
2,train_Client_0,2015-03-23,11,1335667.0,203,1,123,0,0,0,14624,14747,4,1
3,train_Client_0,2015-07-13,11,1335667.0,207,1,102,0,0,0,14747,14849,4,1
4,train_Client_0,2016-11-17,11,1335667.0,207,1,572,0,0,0,15066,15638,12,1